export interface WatchlistInstrument {
  ticker: string;
  name: string;
  sector: string;
}

export const WATCHLIST_UNIVERSE_VERSION = "v1-us-largecap-100";

export const WATCHLIST_UNIVERSE: WatchlistInstrument[] = [
  { ticker: "AAPL", name: "Apple", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA", sector: "Technology" },
  { ticker: "AMZN", name: "Amazon", sector: "Consumer Discretionary" },
  { ticker: "GOOGL", name: "Alphabet", sector: "Communication Services" },
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services" },
  { ticker: "TSLA", name: "Tesla", sector: "Consumer Discretionary" },
  { ticker: "AVGO", name: "Broadcom", sector: "Technology" },
  { ticker: "BRK-B", name: "Berkshire Hathaway Class B", sector: "Financials" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { ticker: "V", name: "Visa", sector: "Financials" },
  { ticker: "MA", name: "Mastercard", sector: "Financials" },
  { ticker: "WMT", name: "Walmart", sector: "Consumer Staples" },
  { ticker: "COST", name: "Costco", sector: "Consumer Staples" },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer", sector: "Healthcare" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { ticker: "DHR", name: "Danaher", sector: "Healthcare" },
  { ticker: "AMGN", name: "Amgen", sector: "Healthcare" },
  { ticker: "BMY", name: "Bristol Myers Squibb", sector: "Healthcare" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { ticker: "CI", name: "Cigna", sector: "Healthcare" },
  { ticker: "HUM", name: "Humana", sector: "Healthcare" },
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { ticker: "CVX", name: "Chevron", sector: "Energy" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy" },
  { ticker: "SLB", name: "Schlumberger", sector: "Energy" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities" },
  { ticker: "EXC", name: "Exelon", sector: "Utilities" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { ticker: "LOW", name: "Lowe's", sector: "Consumer Discretionary" },
  { ticker: "NKE", name: "Nike", sector: "Consumer Discretionary" },
  { ticker: "MCD", name: "McDonald's", sector: "Consumer Discretionary" },
  { ticker: "SBUX", name: "Starbucks", sector: "Consumer Discretionary" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Industrials" },
  { ticker: "DIS", name: "Walt Disney", sector: "Communication Services" },
  { ticker: "NFLX", name: "Netflix", sector: "Communication Services" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { ticker: "VZ", name: "Verizon", sector: "Communication Services" },
  { ticker: "T", name: "AT&T", sector: "Communication Services" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { ticker: "CMCSA", name: "Comcast", sector: "Communication Services" },
  { ticker: "ORCL", name: "Oracle", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { ticker: "QCOM", name: "Qualcomm", sector: "Technology" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology" },
  { ticker: "INTC", name: "Intel", sector: "Technology" },
  { ticker: "IBM", name: "IBM", sector: "Technology" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { ticker: "CRWD", name: "CrowdStrike", sector: "Technology" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology" },
  { ticker: "PYPL", name: "PayPal", sector: "Financials" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "BLK", name: "BlackRock", sector: "Financials" },
  { ticker: "SPGI", name: "S&P Global", sector: "Financials" },
  { ticker: "BAC", name: "Bank of America", sector: "Financials" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financials" },
  { ticker: "C", name: "Citigroup", sector: "Financials" },
  { ticker: "AXP", name: "American Express", sector: "Financials" },
  { ticker: "PLD", name: "Prologis", sector: "Real Estate" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate" },
  { ticker: "EQIX", name: "Equinix", sector: "Real Estate" },
  { ticker: "CAT", name: "Caterpillar", sector: "Industrials" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials" },
  { ticker: "RTX", name: "RTX", sector: "Industrials" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { ticker: "BA", name: "Boeing", sector: "Industrials" },
  { ticker: "HON", name: "Honeywell", sector: "Industrials" },
  { ticker: "MMM", name: "3M", sector: "Industrials" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { ticker: "FDX", name: "FedEx", sector: "Industrials" },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrials" },
  { ticker: "CSX", name: "CSX", sector: "Industrials" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Industrials" },
  { ticker: "LIN", name: "Linde", sector: "Materials" },
  { ticker: "APD", name: "Air Products and Chemicals", sector: "Materials" },
  { ticker: "NEM", name: "Newmont", sector: "Materials" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { ticker: "KO", name: "Coca-Cola", sector: "Consumer Staples" },
  { ticker: "PEP", name: "PepsiCo", sector: "Consumer Staples" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { ticker: "PM", name: "Philip Morris", sector: "Consumer Staples" },
  { ticker: "MO", name: "Altria", sector: "Consumer Staples" },
];
